sudo: required
services:
  - docker_container

before_install:
  - docker build -t fcaico/docker-react -f Dockerfile.dev . 
  
script:
  - docker run -e CI=true fcaico/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-364871806390"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"    
